# Generated by Django 3.2.6 on 2021-08-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='rolled_over',
            field=models.BooleanField(default=False),
        ),
    ]
