# Generated by Django 3.2.6 on 2021-08-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcalendar', '0003_auto_20210810_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('done', 'Done'), ('archived', 'Archived')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('done', 'Done'), ('archived', 'Archived')], default='todo', max_length=20),
        ),
    ]
